#!/usr/bin/env python3
"""
Generates a disposable stress-test corpus at tests/stress_data/ plus a
verification manifest at tests/stress_data_manifest.json.

Nothing under stress_data/ is meant to be committed — it's regenerated by
running this script (deterministic, seeded). Re-run any time to rebuild:

    docker compose run --rm securescan-cpu python tests/make_stress_data.py

Layout:
  - ~150 filler files (.txt/.csv/.md/.log/.py/.json), sizes 1KB-5MB, spread
    across a directory tree 4-5 levels deep. Filler content is deliberately
    PII-free so it can't be confused with the salted signal below.
  - ~22 "salted" files with real, checksum-valid PII (SIN, credit card,
    fake AWS credentials, email) inserted at a recorded line, so a scan of
    the corpus can be checked against stress_data_manifest.json.
  - A handful of edge cases: a 0-byte file, a unicode torture file, a ~3MB
    single-line file, and a file buried 13 directories deep.

SIN/credit-card validity is checked with the project's own validators
(imported below) rather than reimplemented, so salted values are guaranteed
to pass the same checks the scanner uses.
"""

import json
import os
import random
import shutil
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from detectors.detectors import luhn_check  # noqa: E402
from detectors.keyword_detector import validate_sin  # noqa: E402

SEED = 1337
random.seed(SEED)

OUTPUT_ROOT = os.path.join(PROJECT_ROOT, "tests", "stress_data")
MANIFEST_PATH = os.path.join(PROJECT_ROOT, "tests", "stress_data_manifest.json")

WORDS = (
    "report quarterly revenue analysis customer engagement platform migration "
    "database schema update security audit compliance framework logistics "
    "inventory shipment vendor contract renewal budget forecast headcount "
    "roadmap sprint backlog release deployment pipeline latency throughput "
    "region cluster node service endpoint token session cache queue worker "
    "ledger invoice payment reconciliation onboarding training policy escalation "
    "incident postmortem outage dashboard metric alert threshold retention "
    "archive backup snapshot rollout rollback staging production sandbox"
).split()

NAMES = [
    "Alex Chen", "Priya Nair", "Jordan Blake", "Sofia Marchetti", "Liam O'Connor",
    "Amara Okafor", "Wei Zhang", "Noah Kaplan", "Ines Fontaine", "Taro Yamada",
]

DIR_LEVELS = [
    ["finance", "hr", "engineering", "legal", "sales", "marketing"],
    ["team_alpha", "team_beta", "team_gamma", "team_delta"],
    ["project_x", "project_y", "project_z"],
    ["archive", "current", "drafts"],
    ["2024", "2025", "2026", "misc"],
]

FILLER_EXTS = [".txt", ".md", ".csv", ".log", ".py", ".json"]

SIZE_TIERS = [
    (1_024, 5 * 1024, 0.45),
    (5 * 1024, 50 * 1024, 0.30),
    (50 * 1024, 500 * 1024, 0.18),
    (500 * 1024, 5 * 1024 * 1024, 0.07),
]

_counter = 0


def next_id():
    global _counter
    _counter += 1
    return _counter


def pick_size():
    r = random.random()
    acc = 0.0
    for lo, hi, weight in SIZE_TIERS:
        acc += weight
        if r <= acc:
            return random.randint(lo, hi)
    return random.randint(*SIZE_TIERS[-1][:2])


def random_dir(min_depth=4, max_depth=5):
    depth = random.randint(min_depth, max_depth)
    parts = [random.choice(DIR_LEVELS[i]) for i in range(depth)]
    path = os.path.join(OUTPUT_ROOT, *parts)
    os.makedirs(path, exist_ok=True)
    return path


def sentence(n_words=12):
    return " ".join(random.choice(WORDS) for _ in range(n_words)).capitalize() + "."


def paragraph(n_sentences=6):
    return " ".join(sentence(random.randint(6, 16)) for _ in range(n_sentences))


# --- filler content builders: keep growing until target_size is reached ---

def fill_txt(target_size):
    parts = []
    size = 0
    while size < target_size:
        p = paragraph()
        parts.append(p)
        size += len(p) + 2
    return "\n\n".join(parts)


def fill_md(target_size):
    parts = [f"# {random.choice(WORDS).title()} Notes\n"]
    size = len(parts[0])
    while size < target_size:
        chunk = f"## {random.choice(WORDS).title()}\n\n{paragraph()}\n\n" + "\n".join(
            f"- {sentence(6)}" for _ in range(3)
        )
        parts.append(chunk)
        size += len(chunk) + 2
    return "\n\n".join(parts)


def fill_csv(target_size):
    header = "id,category,description,amount,region"
    rows = [header]
    size = len(header)
    i = 0
    while size < target_size:
        i += 1
        row = f"{i},{random.choice(WORDS)},{sentence(8).rstrip('.')},{random.randint(10, 99999)}.{random.randint(0,99):02d},{random.choice(['NA','EU','APAC','LATAM'])}"
        rows.append(row)
        size += len(row) + 1
    return "\n".join(rows)


def fill_log(target_size):
    levels = ["INFO", "DEBUG", "WARN", "ERROR"]
    lines = []
    size = 0
    day, hour, minute, sec = 1, 0, 0, 0
    while size < target_size:
        sec += random.randint(1, 45)
        if sec >= 60:
            sec -= 60
            minute += 1
        if minute >= 60:
            minute -= 60
            hour += 1
        if hour >= 24:
            hour -= 24
            day += 1
        ts = f"2026-07-{day:02d} {hour:02d}:{minute:02d}:{sec:02d}"
        line = f"{ts} {random.choice(levels)} {sentence(10)}"
        lines.append(line)
        size += len(line) + 1
    return "\n".join(lines)


def fill_py(target_size):
    parts = [f'"""Auto-generated filler module ({random.choice(WORDS)}).\n\nNot part of the scanner; used only for stress-test corpus bulk."""\n']
    size = len(parts[0])
    i = 0
    while size < target_size:
        i += 1
        name = f"{random.choice(WORDS)}_{i}"
        body = (
            f"def {name}(value):\n"
            f'    """{sentence(8)}"""\n'
            f"    total = 0\n"
            f"    for item in range({random.randint(1, 50)}):\n"
            f"        total += item * {random.randint(1, 9)}\n"
            f"    return total + value\n"
        )
        parts.append(body)
        size += len(body)
    return "\n\n".join(parts)


def fill_json(target_size):
    records = []
    size = 2
    i = 0
    while size < target_size:
        i += 1
        rec = {
            "id": i,
            "category": random.choice(WORDS),
            "description": sentence(10),
            "value": round(random.uniform(1, 99999), 2),
        }
        records.append(rec)
        size += len(json.dumps(rec))
    return json.dumps(records, indent=2)


FILLER_BUILDERS = {
    ".txt": fill_txt,
    ".md": fill_md,
    ".csv": fill_csv,
    ".log": fill_log,
    ".py": fill_py,
    ".json": fill_json,
}


def write_filler_file():
    ext = random.choice(FILLER_EXTS)
    target_size = pick_size()
    content = FILLER_BUILDERS[ext](target_size)
    dirpath = random_dir()
    fname = f"filler_{next_id():04d}{ext}"
    fpath = os.path.join(dirpath, fname)
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(content)
    return fpath, os.path.getsize(fpath)


# --- valid PII generation, reusing the project's own validators ---

def make_valid_sin():
    while True:
        digits = [random.randint(1, 9) if i == 0 else random.randint(0, 9) for i in range(9)]
        if digits[0] == 8:
            continue
        candidate = "".join(map(str, digits))
        if validate_sin(candidate):
            return f"{candidate[0:3]} {candidate[3:6]} {candidate[6:9]}"


def make_valid_card(prefix="4"):
    while True:
        body = [int(c) for c in prefix] + [random.randint(0, 9) for _ in range(15 - len(prefix))]
        for check_digit in range(10):
            candidate = "".join(map(str, body)) + str(check_digit)
            if luhn_check(candidate):
                return f"{candidate[0:4]} {candidate[4:8]} {candidate[8:12]} {candidate[12:16]}"
        # extremely unlikely to fall through; retry with a fresh body
        continue


def make_aws_access_key():
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "AKIA" + "".join(random.choice(alphabet) for _ in range(16))


AWS_SECRET_EXAMPLE = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

EMAIL_DOMAINS = ["examplecorp.com", "acme-industries.net", "globex-holdings.io"]


def make_email():
    name = random.choice(NAMES).lower().replace(" ", ".").replace("'", "")
    return f"{name}@{random.choice(EMAIL_DOMAINS)}"


SALT_LINE_TEMPLATES = {
    ".txt": "Reference note: {label} on file is {value}.",
    ".md": "> **{label}**: `{value}`",
    ".csv": "9999,salted-record,{label} {value},1.00,NA",
    ".log": "2026-07-15 09:12:{sec:02d} ERROR possible leak - {label}: {value}",
    ".py": '# {label} (do not commit): {value}\nSALTED_VALUE = "{value}"',
    ".json": None,  # handled specially, see write_salted_file
}


def locate_line(fpath, needle):
    with open(fpath, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if needle in line:
                return i
    return None


def write_salted_file(ext, label, value, expected_taxonomy, expected_band, dirpath=None, min_score=None, max_score=None, tag=""):
    dirpath = dirpath or random_dir()
    fname = f"salted_{tag or label.lower().replace(' ', '_')}_{next_id():04d}{ext}"
    fpath = os.path.join(dirpath, fname)

    target_size = random.randint(2 * 1024, 30 * 1024)
    filler = FILLER_BUILDERS[ext](target_size)

    if ext == ".json":
        try:
            records = json.loads(filler)
        except Exception:
            records = []
        insert_at = len(records) // 2
        records.insert(insert_at, {"id": 9999, "category": "salted", "note": f"{label}: {value}"})
        content = json.dumps(records, indent=2)
    else:
        lines = filler.split("\n")
        insert_at = len(lines) // 2
        sec = random.randint(0, 59)
        salt_line = SALT_LINE_TEMPLATES[ext].format(label=label, value=value, sec=sec)
        lines.insert(insert_at, salt_line)
        content = "\n".join(lines)

    with open(fpath, "w", encoding="utf-8") as f:
        f.write(content)

    line_no = locate_line(fpath, value)

    return {
        "path": os.path.relpath(fpath, PROJECT_ROOT),
        "category": tag or label,
        "salt_value": value,
        "expected_taxonomy": expected_taxonomy,
        "expected_band": expected_band,
        "min_score": min_score,
        "max_score": max_score,
        "line": line_no,
        "size_bytes": os.path.getsize(fpath),
    }


def build_salted_set():
    manifest = []

    for ext in [".txt", ".md", ".csv", ".log", ".py"]:
        value = make_valid_sin()
        manifest.append(write_salted_file(
            ext, "SIN", value, "identifier.financial.sin", "HIGH",
            min_score=70, max_score=100, tag="sin",
        ))

    card_prefixes = ["4", "4", "51", "55", "37"]
    for ext, prefix in zip([".json", ".txt", ".csv", ".log", ".py"], card_prefixes):
        value = make_valid_card(prefix)
        manifest.append(write_salted_file(
            ext, "Credit card", value, "identifier.financial.credit_card", "HIGH",
            min_score=70, max_score=100, tag="credit_card",
        ))

    for ext in [".py", ".log", ".json"]:
        value = make_aws_access_key()
        manifest.append(write_salted_file(
            ext, "AWS access key", value, "secret.credential.aws_access_key", "HIGH",
            min_score=70, max_score=100, tag="aws_access_key",
        ))
    for ext in [".txt", ".md"]:
        manifest.append(write_salted_file(
            ext, "aws secret access key", AWS_SECRET_EXAMPLE,
            "secret.credential.aws_secret_key", "HIGH",
            min_score=70, max_score=100, tag="aws_secret_key",
        ))

    for ext in [".md", ".csv", ".txt", ".json", ".log"]:
        value = make_email()
        manifest.append(write_salted_file(
            ext, "Contact email", value, "contact.email", "MEDIUM",
            min_score=30, max_score=69, tag="email",
        ))

    return manifest


def build_edge_cases():
    edge_dir = os.path.join(OUTPUT_ROOT, "edge_cases")
    os.makedirs(edge_dir, exist_ok=True)
    manifest = []

    zero_path = os.path.join(edge_dir, "empty_zero_byte.txt")
    open(zero_path, "w").close()

    unicode_path = os.path.join(edge_dir, "weird_unicode.txt")
    unicode_content = (
        "﻿"  # literal BOM character at file start
        "Emoji stress: \U0001F600\U0001F4A9\U0001F9E8\U0001F5FF\n"
        "RTL Arabic: مرحبا بالعالم\n"
        "RTL Hebrew: שלום עולם\n"
        "Zalgo: Z̵̧a̶̡l̷̰g̸̖ó̵!̶̀\n"
        "Zero-width: a​b‌c‍d﻿e\n"
        "Math alphanumeric: \U0001D573\U0001D586\U0001D593\U0001D593\U0001D596\n"
        "Combining overload: é́́́́́́́\n"
        "CJK: 你好世界 こんにちは\n"
    )
    with open(unicode_path, "w", encoding="utf-8") as f:
        f.write(unicode_content)

    long_path = os.path.join(edge_dir, "very_long_single_line.txt")
    email = make_email()
    words = " ".join(random.choice(WORDS) for _ in range(450_000 // 7))
    single_line = words + f" contact {email} for details " + words
    with open(long_path, "w", encoding="utf-8") as f:
        f.write(single_line)
    manifest.append({
        "path": os.path.relpath(long_path, PROJECT_ROOT),
        "category": "email_longline",
        "salt_value": email,
        "expected_taxonomy": "contact.email",
        "expected_band": "MEDIUM",
        "min_score": 30,
        "max_score": 69,
        "line": 1,
        "size_bytes": os.path.getsize(long_path),
    })

    deep_parts = [f"level_{i:02d}" for i in range(13)]
    deep_dir = os.path.join(edge_dir, *deep_parts)
    os.makedirs(deep_dir, exist_ok=True)
    sin_value = make_valid_sin()
    deep_path = os.path.join(deep_dir, "buried_treasure.txt")
    filler = fill_txt(3 * 1024)
    lines = filler.split("\n")
    lines.insert(len(lines) // 2, f"Buried record - SIN on file: {sin_value}.")
    with open(deep_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    manifest.append({
        "path": os.path.relpath(deep_path, PROJECT_ROOT),
        "category": "sin_deep_nested",
        "salt_value": sin_value,
        "expected_taxonomy": "identifier.financial.sin",
        "expected_band": "HIGH",
        "min_score": 70,
        "max_score": 100,
        "line": locate_line(deep_path, sin_value),
        "size_bytes": os.path.getsize(deep_path),
        "depth": len(deep_parts),
    })

    return manifest, [zero_path, unicode_path]


def main():
    if os.path.isdir(OUTPUT_ROOT):
        shutil.rmtree(OUTPUT_ROOT)
    os.makedirs(OUTPUT_ROOT, exist_ok=True)

    print("[+] Writing filler files...")
    filler_files = []
    for _ in range(150):
        filler_files.append(write_filler_file())

    print("[+] Writing salted PII files...")
    salted_manifest = build_salted_set()

    print("[+] Writing edge cases...")
    edge_manifest, edge_plain_paths = build_edge_cases()

    total_files = len(filler_files) + len(salted_manifest) + len(edge_manifest) + len(edge_plain_paths)
    total_bytes = sum(sz for _, sz in filler_files) + sum(m["size_bytes"] for m in salted_manifest + edge_manifest)
    for p in edge_plain_paths:
        total_bytes += os.path.getsize(p)

    manifest = {
        "seed": SEED,
        "generated_files": total_files,
        "total_bytes": total_bytes,
        "salted": salted_manifest + edge_manifest,
        "edge_only": [os.path.relpath(p, PROJECT_ROOT) for p in edge_plain_paths],
    }
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print(f"[✓] Generated {total_files} files, {total_bytes / (1024*1024):.1f} MB total")
    print(f"[✓] Manifest written to {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
