#!/usr/bin/env python3
# tests/test_format_coverage.py
"""
Format-coverage test suite: verifies extraction + detection works across
every supported file format, driven by tests/format_data/manifest.json
(generated by tests/make_format_data.py).

For each manifest file:
  - extract text with the SAME extractor discovery.py would pick for that
    extension (see EXTRACTOR_MAP below),
  - run detect_pii_hybrid(text, run_ner=False) — GLiNER stays off regardless
    of config.py's current GLINER_SKIP_EXTENSIONS, per this suite's own
    contract, not the app's config,
  - for every expected {taxonomy, band} pair, assert it's present in the
    result with the right risk_level,
  - for negative controls, assert the file scores 0.

A FAIL here is diagnostic, not something to patch away — see the printed
extracted text for each failure to tell an extraction gap (text never made
it out of the file) from a detection gap (text is right there, but no
detector fired on it).

Run directly for a pass/fail table + summary:
    docker compose run --rm securescan-cpu python tests/test_format_coverage.py

Also importable / pytest-compatible (test_all_manifest_files).
"""

import json
import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from extractors.text_extractor import extract_text
from extractors.docx_extractor import extract_docx
from extractors.xlsx_extractor import extract_xlsx
from extractors.pdf_extractor import extract_pdf
from extractors.image_extractor import extract_image
from extractors.eml_extractor import extract_eml
from extractors.pptx_extractor import extract_pptx
from detectors.hybrid_detector import detect_pii_hybrid
from scoring import score_file

FORMAT_DATA_DIR = os.path.join(PROJECT_ROOT, "tests", "format_data")
MANIFEST_PATH = os.path.join(FORMAT_DATA_DIR, "manifest.json")

EXTRACTOR_MAP = {
    ".txt": extract_text,
    ".csv": extract_text,
    ".json": extract_text,
    ".py": extract_text,
    ".md": extract_text,
    ".log": extract_text,
    ".docx": extract_docx,
    ".xlsx": extract_xlsx,
    ".pdf": extract_pdf,
    ".png": lambda p: extract_image(p, return_confidence=True)[0],
    ".jpg": lambda p: extract_image(p, return_confidence=True)[0],
    ".jpeg": lambda p: extract_image(p, return_confidence=True)[0],
    ".eml": extract_eml,
    ".pptx": extract_pptx,
}


def extract(path: str) -> str:
    ext = os.path.splitext(path.lower())[1]
    extractor = EXTRACTOR_MAP.get(ext, extract_text)
    return extractor(path)


def load_manifest():
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def check_file(entry):
    """
    Returns (ok: bool, detail: dict) for one manifest file entry.
    detail includes the extracted text and per-expectation results so
    failures are fully diagnosable without re-running anything.
    """
    abs_path = os.path.join(PROJECT_ROOT, entry["path"])
    text = extract(abs_path)
    matches = detect_pii_hybrid(text, run_ner=False)
    score = score_file(matches)

    if entry["negative_control"]:
        ok = score == 0
        return ok, {
            "text": text,
            "score": score,
            "expectation_results": [],
        }

    expectation_results = []
    all_ok = True
    for exp in entry["expected"]:
        taxonomy = exp["taxonomy"]
        band = exp["band"]
        known_fail = exp.get("known_fail", False)
        dets = matches.get(taxonomy, [])
        found = None
        for d in dets:
            if d.get("risk_level") == band:
                found = d
                break
        exp_ok = found is not None

        # A known_fail expectation is a documented, accepted limitation — it
        # is still checked (and reported as XFAIL/XPASS below) but does not
        # count toward the file's overall pass/fail, unlike an ordinary miss.
        if not known_fail:
            all_ok = all_ok and exp_ok

        expectation_results.append({
            "taxonomy": taxonomy,
            "expected_band": band,
            "expected_value": exp["value"],
            "location": exp.get("location"),
            "note": exp.get("note"),
            "known_fail": known_fail,
            "ok": exp_ok,
            "actual": dets,  # everything detected under this taxonomy, for diffing
        })

    return all_ok, {
        "text": text,
        "score": score,
        "expectation_results": expectation_results,
    }


# ============================================================
#  PYTEST-COMPATIBLE TEST
# ============================================================


def test_all_manifest_files():
    manifest = load_manifest()
    failures = []
    for entry in manifest["files"]:
        ok, detail = check_file(entry)
        if not ok:
            failures.append((entry["path"], detail))
    assert not failures, (
        f"{len(failures)} format-coverage file(s) failed: "
        f"{[p for p, _ in failures]}"
    )


# ============================================================
#  SCRIPT MODE — pass/fail table + full diagnostics on failure
# ============================================================

if __name__ == "__main__":
    manifest = load_manifest()
    results = []

    print(f"{'FILE':<32} {'FORMAT':<8} {'SCORE':>5}  RESULT")
    print("-" * 70)

    for entry in manifest["files"]:
        ok, detail = check_file(entry)
        results.append((entry, ok, detail))
        xfail_count = sum(
            1 for er in detail["expectation_results"]
            if er["known_fail"] and not er["ok"]
        )
        suffix = f" (+{xfail_count} known xfail)" if ok and xfail_count else ""
        print(
            f"{os.path.basename(entry['path']):<32} {entry['format']:<8} "
            f"{detail['score']:>5}  {'PASS' if ok else 'FAIL'}{suffix}"
        )

    print("-" * 70)
    n_files = len(results)
    n_failed = sum(1 for _, ok, _ in results if not ok)
    print(f"SUMMARY: {n_files - n_failed}/{n_files} files fully passed, {n_failed} failed")
    print()

    if n_failed:
        print("=" * 70)
        print("FAILURE DETAIL (extracted text + per-expectation diagnosis)")
        print("=" * 70)
        for entry, ok, detail in results:
            if ok:
                continue
            print(f"\n--- {entry['path']} (score={detail['score']}) ---")
            print("EXTRACTED TEXT:")
            print(repr(detail["text"]))
            print()
            if entry["negative_control"]:
                print(f"  Negative control expected score=0, got {detail['score']}")
            for er in detail["expectation_results"]:
                if er["ok"] or er["known_fail"]:
                    continue
                print(f"  MISSING: {er['taxonomy']} (expected band={er['expected_band']}, "
                      f"expected value~={er['expected_value']!r}, location={er['location']})")
                if er["note"]:
                    print(f"    note: {er['note']}")
                print(f"    actual detections under this taxonomy: {er['actual']}")

    # Known limitations are checked every run (not skipped), reported here
    # regardless of overall pass/fail — XFAIL means "still failing as
    # documented"; XPASS means the limitation is gone and the manifest's
    # known_fail flag should be removed.
    xfail_entries = [
        (entry, er)
        for entry, _, detail in results
        for er in detail["expectation_results"]
        if er["known_fail"]
    ]
    if xfail_entries:
        print("=" * 70)
        print("KNOWN LIMITATIONS (documented known_fail expectations)")
        print("=" * 70)
        for entry, er in xfail_entries:
            status = "XPASS (limitation resolved — update the manifest)" if er["ok"] else "XFAIL (as documented)"
            print(f"  {os.path.basename(entry['path']):<24} {er['taxonomy']:<40} {status}")

    sys.exit(1 if n_failed else 0)
